### ISSUE TITLE
[FEATURE] K-평균 군집화 페이지 구현

### ISSUE THREAD

**Issue by yerim8373** [KccLast/FillIn#69]
## 설명
> K-평균 군집화 페이지 구현

## TO-DO
- [x] 군집화 개수 설정 후 그래프 보여주기
- [x]  군집화 페이지 UI
- [x]  군집화 기능 api 구현

## 기타(참고, 스크린샷 등등)
> 기타 사항을 작성해주세요.
